version = 2
root = "/var/lib/containerd"
state = "/run/k3s/containerd"
plugin_dir = ""
disabled_plugins = []
required_plugins = []
oom_score = 0
[grpc]
  address = "/run/k3s/containerd/containerd.sock"
  uid = 0
  gid = 0
