#!/bin/bash

K3STOKENSTORE=/var/lib/rancher/k3s/server/token
echo k3 token stored in ${K3STOKENSTORE}

echo secret only:
sed -e 's/.*server:\(.*\)/\1/' ${K3STOKENSTORE}
echo
echo "full contents>"
cat ${K3STOKENSTORE}
