#!/bin/bash
# this needs gnu sed !

HNAME=$(hostname)

if [ ! -f /etc/hosts ] ; then
  echo -ne "/etc/hosts missing "
  touch /etc/hosts
  echo "... created"
else 
  echo "/etc/host exists"
fi

HFOUND=$(grep ${HNAME} /etc/hosts | wc -l)
if [ "X${HFOUND}" == "X" ] ; then
  echo -ne "/etc/hosts doesn't contain ${HNAME} "
  sed "/^127\.0\.0\.1/{h;s/\(.*\)/\1 ${HNAME}/};\${x;/^$/{s//127.0.0.1 localhost ${HNAME}/;H};x}" /etc/hosts
  echo "... added 127.0.0.1 localhost ${HNAME}"
fi
