#!/bin/bash

SERVICE="/etc/systemd/system/k3s.service"

echo -ne "systemd service"

if [ ! -f "${SERVICE}" ] ; then
  echo -ne " ... installing"
  cp `basename $SERVICE` "$SERVICE"
  echo " ... done"
else
  echo " ... already installed"
fi

