#!/bin/bash

DELDIRS="/run/flannel /var/lib/rancher/k3s /var/lib/kubelet /etc/cni/net.d /root/.kube"

for dir in $DELDIRS; do
	echo deleting $dir
	rm -rf $dir
done

systemctl stop k3s.service

rm -f /etc/systemd/system/k3s.service*
systemctl daemon-reload

