#!/bin/bash

echo "configure cloud provider rbac"
kubectl create -f https://raw.githubusercontent.com/plunder-app/plndr-cloud-provider/master/example/pod/rbac.yaml

echo "deploying loadbalancer"
curl https://raw.githubusercontent.com/plunder-app/plndr-cloud-provider/master/example/pod/plndr-cloud-provider.yaml

echo "deploy starboard daemonset"
#k create -f https://raw.githubusercontent.com/plunder-app/starboard/master/examples/daemonset/0.1.yaml
