# file: ~/auth/ldap-admin.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldapadmin-config
  namespace: auth
  labels:
    app: ldap
    tier: frontend
data:
  PHPLDAPADMIN_LDAP_HOSTS: "ldap.auth"
  PHPLDAPADMIN_HTTPS: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: ldapadmin
  namespace: auth
  labels:
    app: ldap
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: ldap
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldapadmin-deployment
  namespace: auth
  labels:
    app: ldap
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ldap
        tier: frontend
    spec:
      containers:
      - name: ldapadmin
        image: osixia/phpldapadmin
        envFrom:
        - configMapRef:
            name: ldapadmin-config
        ports:
        - containerPort: 80
          name: http
